#!/bin/zsh

sleep 1 # if ran at boot time

# To show the devices
# xsetwacom list devices

# Set the cursor to be relative
xsetwacom set "Wacom Intuos PT S 2 Finger touch" Mode Relative
# xsetwacom set "Wacom Intuos PT S 2 Pen stylus" Mode Relative

# eraser
xsetwacom set "Wacom Intuos PT S 2 Pad pad" Button 1 "key e"
# free brush
xsetwacom set "Wacom Intuos PT S 2 Pad pad" Button 2 "key b"
#xsetwacom set "Wacom Intuos PT S 2 Pad pad" Button 3 "key \+"

