" User vim configuration
" Pathogen started(disabled by default)
"execute pathogen#infect()

" Basic configuration
syntax on		    " Enables file syntax
filetype plugin indent on   " For pathogen
set hlsearch		    " Highlight all search results
set number		    " Show line numbers
set autoindent		    " Auto-indent new lines
set shiftwidth=4	    " Number of auto-indent spaces
set smartindent		    " Enable smart-indent
set smarttab		    " Enable smart-tabs
set softtabstop=4	    " Number of spaces per tab
