" User vim configuration
"
" Plugins(Powered by Plug)
call plug#begin('~/.vim/plugged')
" For syntax errors
Plug 'vim-syntastic/syntastic'

" For the fancy indicator bar
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

" Git bar support
Plug 'tpope/vim-fugitive'

" Icons for the bar
Plug 'ryanoasis/vim-devicons'

" Colorscheme
Plug 'arcticicestudio/nord-vim'
call plug#end()

" Basic configuration
syntax on				" Enables file syntax
set encoding=utf-8			" Required to insert unicode characters
set nohlsearch				" Stops highlighting search results
set number relativenumber		" Show line numbers
" Spacing configuration
set autoindent				" Auto-indent new lines
set shiftwidth=4			" Number of auto-indent spaces
set smartindent				" Enable smart-indent
set smarttab				" Enable smart-tabs
set softtabstop=4			" Number of spaces per Tab

set splitbelow splitright		" Changes split orientation

set foldmethod=indent			" Enables fold code

" For airline support
"let g:airline_theme='ravenpower'	" Fallback theme
let g:airline_theme='nord'
let g:airline_powerline_fonts = 1

" Language specific
" HTML
autocmd Filetype html setlocal shiftwidth=2 softtabstop=2
autocmd Filetype css setlocal shiftwidth=2 softtabstop=2
autocmd Filetype javascript setlocal shiftwidth=2 softtabstop=2
